# This is a basic workflow to help you get started with Actions

name: Dump Supabase Schema

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: dump postgres schema
        uses: addnab/docker-run-action@v3
        with:
          image: supabase/pgadmin-schema-diff
          options: "'${{ secrets.SUPABASE_DB_CONNECTION_STRING }}' '${{ secrets.SUPABASE_EMPTY_DB_CONNECTION_STRING }}' > ./supabase/schema.sql"
      - name: check for file changes
        id: git_status
        run: |
          echo "::set-output name=status::$(git status -s)"
      - name: commit file
        if: ${{contains(steps.git_status.outputs.status, ' ')}}
        run: |
          git add .supabase/schema.sql
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update supabase schema" -a
      - name: push changes
        if: ${{contains(steps.git_status.outputs.status, ' ')}}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
